CREATE DATABASE IF NOT EXISTS VapesElPipe;

USE VapesElPipe;

CREATE TABLE IF NOT EXISTS Customers(
IDCustomer INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NameCostomers VARCHAR(100)

);

CREATE TABLE IF NOT EXISTS Vapes(
IDVapes INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NameVapes VARCHAR(100),
VapesFlavors VARCHAR(100),
VapesHits VARCHAR(100),
VapesPrice INT
);

CREATE TABLE IF NOT EXISTS Tools(
IDTools INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NameTools VARCHAR(100),
PriceTools int,
BrandTools VARCHAR(100)
);
CREATE TABLE IF NOT EXISTS Accessories(
IDAccessories INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NameAccessories VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS ELiquids(
IDELiquids INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
NameELiquids VARCHAR(100)
);
